### ISSUE TITLE
limma missing

### ISSUE THREAD

**Issue by frederikziebell** [cran-task-views/Omics#2]
[limma](https://bioconductor.org/packages/release/bioc/html/limma.html) is one of the most popular packages on Bioconductor, it should be mentioned

**Comment by tuxette** [comment]
Yes, sure! Sorry for missing it. I'll add it today or tomorrow at most. Thanks!

**Comment by tuxette** [comment]
fixed in commit 0374655e2624d9fc1d68847dc2c1cb5b713a8b77
