### ISSUE TITLE
Removed Bioconductor packages

### ISSUE THREAD

**Issue by zeileis** [cran-task-views/Omics#3]
As pointed out in PR https://github.com/cran-task-views/Omics/pull/1 the `DESeq` package was removed from Bioconductor and superseded by `DESeq2`. I have already approved the PR and updated the CRAN page.

Doing so I noticed that three other packages that the Omics view currently (tries to) link(s) are deprecated and removed from current versions from Bioconductor:  [ChIPSeqSpike](https://bioconductor.org/packages/3.13/bioc/html/ChIPSeqSpike.html), [DBChIP](https://bioconductor.org/packages/3.13/bioc/html/DBChIP.html), [triform](https://bioconductor.org/packages/3.11/bioc/html/triform.html).

I'm not so familiar with Bioconductor but I suspect that it would be most appropriate to remove these from the CRAN task view as well? Possibly there are replacement packages that are still included in current Bioconductor versions? If necessary/appropriate, you can of course, create a link to old versions of the package but you currently cannot use the `r bioc("...")` tag for that.

**Comment by HenrikBengtsson** [comment]
Related to this: The canonical URL (aka "Package Short Url") for a Bioconductor package has the format `https://www.bioconductor.org/packages/<pkgname>`, e.g. https://www.bioconductor.org/packages/ChIPSeqSpike.  

If the package is deprecated/removed, that will 302 redirect to the correct location, e.g.

```r
$ curl --head https://www.bioconductor.org/packages/ChIPSeqSpike
HTTP/1.1 302 Moved Temporarily
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
Date: Mon, 03 Apr 2023 16:31:43 GMT
Server: Apache/2.4.18 (Ubuntu)
Location: https://bioconductor.org/about/removed-packages/
Cache-Control: max-age=600
Expires: Mon, 03 Apr 2023 16:41:43 GMT
X-Cache: Miss from cloudfront
Via: 1.1 f85d379725bf31eb2428acfa2b9da6e6.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SFO5-P1
X-Amz-Cf-Id: Ht3zrnNfuf8l80SiK9C6exT64L4q-EpkZrjdvvIhnzeqxQgAfnbmHA==
```

**Comment by zeileis** [comment]
Thanks, Henrik! I've updated the R-Forge version of the `ctv` package correspondingly and re-generated all task view HTML pages with it.

I have to say, though, that I find unexpected that even the DOIs like <https://doi.org/10.18129/B9.bioc.triform> redirect to the "Removed Packages" page rather than to the last stable version of the package that was included in Bioconductor.

**Comment by HenrikBengtsson** [comment]
> I've updated the R-Forge version of the ctv package correspondingly and re-generated all task view HTML pages with it.

Great.  I didn't realize it was that easy to do across the board.  Could you then also make Bioconductor packages use 

```html
<span class="BioC">pkgname</span>
```

? That way, they'll be annotated the same way as they're currently done on CRAN package pages, which is currently with a different foreground color than CRAN packages.  See <https://cran.r-project.org/package=PSCBS> for an example.

**Comment by HenrikBengtsson** [comment]
The different span classes are defined in <https://cran.r-project.org/web/CRAN_web.css>, e.g.

```css
span.BioC {
    color: #2C92A1;
}

span.Ohat {
    color: #8A4513;
}

span.Gcode {
    color: #5B8A00;
}

span.Rforge {
    color: #8009AA;
}

span.GitHub {
    color: #9F7BE1;
}
```

**Comment by zeileis** [comment]
Thanks for the reminder, Henrik. We had this in the old XML-based task views but I didn't know how to do this cleanly in pandoc...and then forgot about it. Added now.

**Comment by tuxette** [comment]
Thanks @zeileis and sorry for the bug `DESeq`/`DESeq2`.
@tdhock : I think that you cited these Bioconductor packages for ChiPseq: what do you think? We remove then, don't we?

**Comment by tdhock** [comment]
I did not know that it was inappropriate to mention removed/deprecated packages in a task view, so if that is the case, then that is fine with me to remove them.

**Comment by tuxette** [comment]
fixed in be9d53c1318cbaeb740f843128b9f81ff3833d3b

**Comment by zeileis** [comment]
Just to clarify: I did **not** say that it was inappropriate to link to removed Bioconductor packages.

What I said is that I **suspect** it would be most appropriate to remove them in the task view as well because I assumed that there would be a reason for Bioconductor dropping them (possibly outdated, superseded by other packages etc.). But I also said that I am not too familiar with Bioconductor so I might be wrong with my suspicion above.

So it may well be ok to link to a removed Bioconductor package. But if you want to do so you currently need to use a direct link in the Markdown file and you cannot use the `r bioc(...)` tag.

**Comment by HenrikBengtsson** [comment]
FWIW, I don't think it would be "too hard" to make `r pkg(pkgname)` and `r bioc(pkgname)` check the generated URLs, e.g. if the URL is a 301-redirect, it could generate a warning somewhere, possibly even visual on the page, to highlight that there's been a change upstream.  OTH, maybe there are already HTML URL checkers in place elsewhere for this.

**Comment by zeileis** [comment]
The pkg tags are checked on CRAN. Other links should be checked regularly as well... but not upon creation.

**Comment by tuxette** [comment]
@zeileis For me it makes sense to remove packages deprecated from Bioconductor because we have decided to focus on the top visible packages (otherwise, all Bioc pkg would fit in this TV). Since Toby did not oppose the idea, I removed them yesterday.
