### ISSUE TITLE
Should packages like matrixStats or matrixTests be included?

### ISSUE THREAD

**Issue by karoliskoncevicius** [cran-task-views/Omics#5]
Technically these are not strictly for -omics only. But in practice they are most often used in -omic contexts for fast and convenient computation of various statistics and hypothesis tests on all rows (i.e. genes) in a dataset.

**Comment by tuxette** [comment]
Thanks for the mention! We have discussed that when creating the task view but, considering the very large number of packages focused on omics, we have decided to not include this type of packages. My personal point of view if that they would be more adapted to NumericalMathematics or HighPerformanceComputing maybe.
